// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tzgaxvbeababbqsogqsl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR6Z2F4dmJlYWJhYmJxc29ncXNsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUxNzkyODUsImV4cCI6MjA2MDc1NTI4NX0.kYpcaQKLHlKtkq3mGN5OYlofrRa_1AHVdA1_i83hVtY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);